"""Experimental direction-compatible receiver attribution."""

from .basis import build_gated_target_basis
from .contracts import (
    AttributionResult,
    AttributionSupportMethod,
    BasisBuildReport,
    DownstreamAttributionSupport,
    DriverEstimate,
    DriverFamilyDefinition,
    FamilyAllocationSummary,
    FamilyBasisMethod,
    FamilyEstimate,
    FamilyFirstAllocationResult,
    FamilyFirstAttributionResult,
    FamilyFirstBasis,
    FamilyMemberAllocation,
    FamilyMemberAllocationMethod,
    FamilyMemberEvidence,
    GatedTargetBasis,
    LRIdentifiabilityStatus,
    ObjectiveTerms,
    ReceptorGatePolicy,
    SolverDiagnostics,
    SolverStatus,
)
from .directional import (
    DirectionalResponseChannel,
    ResponseDirection,
    directional_response_channel,
)
from .families import cluster_driver_families
from .family_first import (
    allocate_family_members,
    attribute_target_prior_family_first,
    build_family_first_basis,
    fit_family_first_attribution,
)
from .frozen_family import (
    ReceiverFamilyTrainingArtifact,
    fit_receiver_family_training_artifact,
    fit_receiver_family_training_artifacts,
)
from .model import (
    attribute_target_prior,
    downstream_attribution_support,
    fit_positive_attribution,
)
from .precision import (
    PrecisionTransformResult,
    fit_response_precision,
    winsorized_normalized_precision,
)
from .solver import (
    ElasticNetSolution,
    solve_nonnegative_elastic_net,
    solve_nonnegative_residual_elastic_net,
)
from .tuning import (
    PenaltyCandidateSummary,
    PenaltyFoldEvaluation,
    PenaltyScaleResolution,
    PenaltyTuningArtifact,
    PenaltyTuningSpec,
    RelativePenaltyCandidate,
    ResolvedPenalty,
    record_penalty_fold_evaluation,
    resolve_penalty_scale,
    resolve_residualized_penalty_scale,
    select_penalty_candidate,
)

__all__ = [
    "AttributionResult",
    "AttributionSupportMethod",
    "BasisBuildReport",
    "DirectionalResponseChannel",
    "DownstreamAttributionSupport",
    "DriverEstimate",
    "DriverFamilyDefinition",
    "ElasticNetSolution",
    "FamilyAllocationSummary",
    "FamilyBasisMethod",
    "FamilyEstimate",
    "FamilyFirstAllocationResult",
    "FamilyFirstAttributionResult",
    "FamilyFirstBasis",
    "FamilyMemberAllocation",
    "FamilyMemberAllocationMethod",
    "FamilyMemberEvidence",
    "GatedTargetBasis",
    "LRIdentifiabilityStatus",
    "ObjectiveTerms",
    "PenaltyCandidateSummary",
    "PenaltyFoldEvaluation",
    "PenaltyScaleResolution",
    "PenaltyTuningArtifact",
    "PenaltyTuningSpec",
    "PrecisionTransformResult",
    "ReceiverFamilyTrainingArtifact",
    "ReceptorGatePolicy",
    "RelativePenaltyCandidate",
    "ResolvedPenalty",
    "ResponseDirection",
    "SolverDiagnostics",
    "SolverStatus",
    "allocate_family_members",
    "attribute_target_prior",
    "attribute_target_prior_family_first",
    "build_family_first_basis",
    "build_gated_target_basis",
    "cluster_driver_families",
    "directional_response_channel",
    "downstream_attribution_support",
    "fit_family_first_attribution",
    "fit_positive_attribution",
    "fit_receiver_family_training_artifact",
    "fit_receiver_family_training_artifacts",
    "fit_response_precision",
    "record_penalty_fold_evaluation",
    "resolve_penalty_scale",
    "resolve_residualized_penalty_scale",
    "select_penalty_candidate",
    "solve_nonnegative_elastic_net",
    "solve_nonnegative_residual_elastic_net",
    "winsorized_normalized_precision",
]
