"""Pure component integration for sample-level communication strength."""

from __future__ import annotations

import math
from collections.abc import Mapping
from typing import Any, cast

import numpy as np
import pandas as pd

from .contracts import (
    SCORE_COLUMNS,
    CommunicationScores,
    CommunicationScoreStatus,
    ScoringFunctional,
)

_AVAILABILITY_KEYS = [
    "sample_id",
    "subject_id",
    "context",
    "sender",
    "receiver",
    "interaction_id",
]
_JOIN_KEYS = ["sample_id", "subject_id", "context", "receiver", "interaction_id"]
_AVAILABILITY_COLUMNS = {
    *_AVAILABILITY_KEYS,
    "state_availability",
    "ecosystem_availability",
    "sender_component",
}
_DOWNSTREAM_COLUMNS = {*_JOIN_KEYS, "downstream_activity", "prior_quality"}


def _numeric_component(value: object, *, name: str) -> float | None:
    if value is None or value is pd.NA:
        return None
    try:
        numeric = float(cast(Any, value))
    except (TypeError, ValueError) as error:
        raise ValueError(f"{name} must contain numeric values or NA") from error
    if math.isnan(numeric):
        return None
    if not math.isfinite(numeric) or not 0 <= numeric <= 1:
        raise ValueError(f"{name} values must be finite and lie in [0, 1]")
    return numeric


def weighted_geometric_strength(
    components: Mapping[str, float | None],
    weights: Mapping[str, float],
    scales: Mapping[str, float] | None = None,
) -> float | None:
    """Return a normalized weighted geometric mean, propagating missing values."""

    if set(components) != set(weights):
        raise ValueError("components and weights must have identical keys")
    component_scales = scales or dict.fromkeys(components, 1.0)
    if set(component_scales) != set(components):
        raise ValueError("component scales must have the same keys as components")
    active: list[tuple[float, float]] = []
    for name, raw_weight in weights.items():
        weight = float(raw_weight)
        scale = float(component_scales[name])
        if not math.isfinite(weight) or weight < 0:
            raise ValueError(
                f"component weight {name!r} must be finite and non-negative"
            )
        if not math.isfinite(scale) or scale <= 0:
            raise ValueError(f"component scale {name!r} must be finite and positive")
        if weight == 0:
            continue
        value = _numeric_component(components[name], name=name)
        if value is None:
            return None
        active.append((min(value / scale, 1.0), weight))
    if not active:
        raise ValueError("at least one component weight must be positive")
    if any(value == 0 for value, _ in active):
        return 0.0
    weight_sum = sum(weight for _, weight in active)
    log_strength = sum(weight * math.log(value) for value, weight in active)
    return float(math.exp(log_strength / weight_sum))


def _require_columns(table: pd.DataFrame, required: set[str], *, name: str) -> None:
    missing = required.difference(table.columns)
    if missing:
        raise ValueError(f"{name} table is missing columns: {sorted(missing)}")


def _validate_identifiers(
    table: pd.DataFrame, columns: list[str], *, name: str
) -> None:
    for column in columns:
        if table[column].isna().any():
            raise ValueError(f"{name}.{column} must not contain missing identifiers")


def _validate_function_tags(
    table: pd.DataFrame,
    functional: ScoringFunctional,
    *,
    name: str,
) -> pd.DataFrame:
    result = table.copy(deep=True)
    if "scoring_function_id" in result:
        identifiers = set(result["scoring_function_id"].dropna())
        if identifiers != {functional.scoring_function_id}:
            raise ValueError(
                f"{name} table was not generated by the supplied scoring functional"
            )
        result = result.drop(columns="scoring_function_id")
    elif functional.is_out_of_fold:
        raise ValueError(
            f"out-of-fold {name} table must carry scoring_function_id provenance"
        )
    return result


def _missing_reason(
    components: Mapping[str, float | None], weights: Mapping[str, float]
) -> str:
    missing = sorted(
        name
        for name, value in components.items()
        if weights[name] > 0 and value is None
    )
    return "missing_core_evidence:" + ",".join(missing)


def score_communication(
    availability: pd.DataFrame,
    downstream_activity: pd.DataFrame,
    functional: ScoringFunctional,
) -> CommunicationScores:
    """Merge sample components and calculate state/ecosystem communication strength.

    ``availability`` defines candidate sender-receiver edges. Downstream rows are
    joined without sender identity and may therefore be reused for candidate
    senders of the same sample, receiver, and interaction. No statistical test
    or probability calibration is performed.
    """

    if not isinstance(functional, ScoringFunctional):
        raise TypeError("functional must be a ScoringFunctional")
    _require_columns(availability, _AVAILABILITY_COLUMNS, name="availability")
    _require_columns(downstream_activity, _DOWNSTREAM_COLUMNS, name="downstream")
    _validate_identifiers(availability, _AVAILABILITY_KEYS, name="availability")
    _validate_identifiers(downstream_activity, _JOIN_KEYS, name="downstream")
    if availability.duplicated(_AVAILABILITY_KEYS).any():
        raise ValueError("availability sample-edge rows must be unique")
    if downstream_activity.duplicated(_JOIN_KEYS).any():
        raise ValueError("downstream sample-interaction rows must be unique")

    availability_copy = _validate_function_tags(
        availability, functional, name="availability"
    )
    downstream_copy = _validate_function_tags(
        downstream_activity, functional, name="downstream"
    )
    observed_contexts = set(availability_copy["context"])
    unknown_contexts = observed_contexts.difference(functional.contrast_contexts)
    if unknown_contexts:
        raise ValueError(
            f"availability contains contexts outside the functional: {unknown_contexts}"
        )
    if functional.is_out_of_fold and observed_contexts != set(
        functional.contrast_contexts
    ):
        raise ValueError("out-of-fold input must contain every contrast context")
    unknown_interactions = set(availability_copy["interaction_id"]).difference(
        functional.interaction_ids
    )
    if unknown_interactions:
        raise ValueError(
            "availability contains interactions outside the frozen universe: "
            f"{sorted(unknown_interactions)}"
        )
    if functional.is_out_of_fold:
        leakage = set(availability_copy["subject_id"]).intersection(
            functional.training_subject_ids
        )
        if leakage:
            raise ValueError(
                "out-of-fold scoring has training/test subject overlap: "
                f"{sorted(leakage)}"
            )

    merged = availability_copy.merge(
        downstream_copy,
        how="left",
        on=_JOIN_KEYS,
        validate="many_to_one",
        sort=False,
    )
    if "abundance_component" not in merged:
        merged["abundance_component"] = np.nan
    for column in (
        "state_availability",
        "ecosystem_availability",
        "sender_component",
        "downstream_activity",
        "prior_quality",
        "abundance_component",
    ):
        for value in merged[column]:
            _numeric_component(value, name=column)

    output_rows: list[dict[str, Any]] = []
    fold_id = functional.fold_id or "in_sample"
    for _, row in merged.iterrows():
        for mode, availability_column in (
            ("state", "state_availability"),
            ("ecosystem", "ecosystem_availability"),
        ):
            component_values = {
                "availability": _numeric_component(
                    row[availability_column], name=availability_column
                ),
                "downstream": _numeric_component(
                    row["downstream_activity"], name="downstream_activity"
                ),
                "sender": _numeric_component(
                    row["sender_component"], name="sender_component"
                ),
                "prior_quality": _numeric_component(
                    row["prior_quality"], name="prior_quality"
                ),
            }
            strength = weighted_geometric_strength(
                component_values,
                functional.component_weights,
                functional.component_scales,
            )
            if strength is None:
                status = CommunicationScoreStatus.MISSING_CORE_EVIDENCE.value
                reason_code: str | None = _missing_reason(
                    component_values, functional.component_weights
                )
            else:
                status = CommunicationScoreStatus.OK.value
                reason_code = None
            output_rows.append(
                {
                    **{key: row[key] for key in _AVAILABILITY_KEYS},
                    "mode": mode,
                    "availability": component_values["availability"],
                    "downstream_activity": component_values["downstream"],
                    "sender_component": component_values["sender"],
                    "prior_quality": component_values["prior_quality"],
                    "abundance_component": _numeric_component(
                        row["abundance_component"], name="abundance_component"
                    ),
                    "comm_strength": strength,
                    "status": status,
                    "reason_code": reason_code,
                    "functional_status": functional.status.value,
                    "functional_reason_code": functional.reason_code,
                    "contrast": functional.contrast_name,
                    "fold_id": fold_id,
                    "scoring_function_id": functional.scoring_function_id,
                    "interaction_universe_id": functional.interaction_universe_id,
                    "target_universe_id": functional.target_universe_id,
                }
            )
    table = pd.DataFrame(output_rows, columns=sorted(SCORE_COLUMNS))
    if not table.empty:
        table = table.sort_values(
            [
                "sample_id",
                "context",
                "sender",
                "receiver",
                "interaction_id",
                "mode",
            ],
            kind="stable",
            ignore_index=True,
        )
    return CommunicationScores(table=table, functional=functional)
